import React from 'react';
import Container from "react-bootstrap/Container";
import Head from "next/head";
import Layout from "@/components/Layout";

function Activation(props) {
    return (<>
        <Head>
            <title>Dreamcast - Activation</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.png"/>
        </Head>
        <main>
            <Layout>
                <section className="gray-bg work-page" id={'workActivation'}>
                    <Container>
                        <div className="row g-2">
                            <div className="col-md-6 col-sm-6 col-6">
                                <div className="event-card" style={{backgroundImage: 'url(./images/work/kidsparadise.png)'}}>
                                    <a href={'#'} className="event-card-content">
                                        <h3 className="event-title">Kids Paradise</h3>
                                    </a>
                                </div>
                            </div>
                            <div className="col-md-6 col-sm-6 col-6">
                                <div className="event-card"
                                     style={{backgroundImage: 'url(./images/work/foodbank.png)'}}>
                                    <div className="event-card-content">
                                        <h3 className="event-title">Food Bank</h3>
                                    </div>
                                </div>
                            </div>
                            <div className="col-md-3 col-sm-6 col-6">
                                <div className="event-card" style={{backgroundImage: 'url(./images/work/arong.png)'}}>
                                    <div className="event-card-content">
                                        <h3 className="event-title">Aarong</h3>
                                    </div>
                                </div>
                            </div>
                            <div className="col-md-6 col-sm-6 col-6">
                                <div className="event-card" style={{backgroundImage: 'url(./images/work/ky.png)'}}>
                                    <div className="event-card-content">
                                        <h3 className="event-title">KY Steel</h3>
                                    </div>
                                </div>
                            </div>
                            <div className="col-md-3 col-sm-6 col-6">
                                <div className="event-card" style={{backgroundImage: 'url(./images/work/oppo.jpg)'}}>
                                    <div className="event-card-content">
                                        <h3 className="event-title">Oppo</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <img src="./images/work/go-on.png" alt="The Show must be Go on" className="goon-image"/>
                    </Container>
                </section>
            </Layout>
        </main>
    </>);
}

export default Activation;