import Head from 'next/head'
import Layout from "@/components/Layout";
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import { Autoplay, Navigation } from 'swiper/modules';
import Container from "react-bootstrap/Container";
import Clients from "@/components/Home/Clients";
import Team from "@/components/Home/Team";
import Contact from "@/components/Home/Contact";
import Event from "@/components/Home/Event";

// export async function getServerSideProps() {
//
//   let packages= await fetch('',
//     {
//       method: 'GET',
//       headers: {
//         'X-Signature': '$2y$10$9L9esFRwXcOEycuR6BQTQemaptI43YxWa0Sf1lSv5X87yhT2ZiDH.',
//       }})
//   packages= await packages.json()
//   return { props: { packages } }
// }

export default function Home() {
  const  packagesShort = [{
      title: "Event ",
      slug: 'event',
      id: 12
    }
  ]
  return (
    <>
      <Head>
        <title>Dreamcast</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.png"/>
      </Head>
      <main>
        <Layout packages={packagesShort}>
            <section id={'home'}>
                    <Container>
                        <Swiper
                            spaceBetween={30}
                            centeredSlides={true}
                            autoplay={{
                                delay: 2500,
                                disableOnInteraction: false,
                            }}
                            pagination={{
                                clickable: true,
                            }}
                            navigation={true}
                            modules={[Autoplay, Navigation]}
                            className="mySwiper header-swiper mt-2"
                        >
                            <SwiperSlide>
                                <img src="./images/home-banner-2.png" alt="Banner"/>
                            </SwiperSlide>
                            <SwiperSlide>
                                <img src="./images/home-banner.png" alt="Banner"/>
                            </SwiperSlide>
                        </Swiper>
                        <div className="row justify-content-center align-items-center g-4 mt-2">
                            <div className="col-7 col-sm-6 col-md-4 col-xl-3">
                                <img className="w-100" src="./images/since.png" alt="Since"/>
                            </div>
                            <div className="col-7 col-sm-6 col-md-3">
                                <div className="position-relative md-image-wrap">
                                    <img className="w-100" src="./images/ceo.png" alt="CEO"/>
                                </div>
                            </div>
                            <div className="col-12 col-md-5 col-xl-4">
                                <img className="quote-icon" src="./images/quote.png" alt="Quote"/>
                                <h1 className="md-speach "><span>The Success</span> of Your Brand
                                    Depends on Its Consistency
                                    & Continuity.</h1>
                                <div className="d-flex">
                                    <p className=""></p>
                                    <div className="">
                                        <p className=""></p>
                                        <p className=""></p>
                                        <p className=""></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </Container>
                </section>
            <Clients />
            <Team />
            <Event />
            <Contact />
        </Layout>
      </main>
    </>
  )
}
